name: Build images using github actions

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  create_empty_uboot_env_partition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # action is based on https://gitlab.com/pgwipeout/quartz64_ci/-/blob/main/.gitlab-ci.yml
      - name: Install dosfstools
        run: sudo apt -y install dosfstools
      - name: Create u-boot environment partition
        run: |
          fallocate -l 4MB data_part_uboot_env.bin
          mkfs.vfat data_part_uboot_env.bin

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: data_part_uboot_env
          path: data_part_uboot_env.bin

  compile_uboot:
    runs-on: ubuntu-latest
    name: compile uboot for the PineNote
    steps:
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential crossbuild-essential-arm64 device-tree-compiler python3-pyelftools
      - name: Checkout rkbin
        run: |
          test -d rkbin || git clone --depth 1 --branch master https://github.com/rockchip-linux/rkbin.git
          test -d u-boot-pinenote || git clone --branch branch_cyttsp5ub --depth 1 https://github.com/m-weigand/u-boot-pinenote
          cd u-boot-pinenote
          export CROSS_COMPILE=aarch64-linux-gnu-
          make clean;
          make rk3566-pinenote_defconfig;
          ./make.sh
          ./make.sh trust
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: uboot-files
          path: |
            u-boot-pinenote/uboot.img
            u-boot-pinenote/trust.img
            u-boot-pinenote/idblock.bin

  generate_spl_boot_file:
    runs-on: ubuntu-latest
    name: Geneate rk356x_spl_loader_v1.12.112.bin
    steps:
      - name: Prepare environment
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential crossbuild-essential-arm64 device-tree-compiler python3-pyelftools
      - name: Checkout rkbin
        run: |
          test -d rkbin && rm -rf rkbin
          git clone --shallow-since="2022-01-02T00:00:00Z" https://github.com/rockchip-linux/rkbin
          cd rkbin
          git checkout b6354b9
          tools/boot_merger RKBOOT/RK3566MINIALL.ini
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: rk356x_spl_loader_v1.12.112.bin
          path: |
            rkbin/rk356x_spl_loader_v1.12.112.bin

  generate_logo_partition:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt -y update && sudo apt install python3-pillow imagemagick libpng-dev cmake fonts-freefont-ttf tree

    - name: Prepare Compilation of logotool
      run: cd custom_logos_uboot/logotool_mod; mkdir build; cd build; cmake ../

    - name: Compilation of logotool
      run: cd custom_logos_uboot/logotool_mod/build; make

    - name: Generate free logos
      run: cd custom_logos_uboot && ./01_draw_free_logos.py

    - name: Generate default bootmenu entries
      run: cd custom_logos_uboot && ./02_gen_default_bootmenu_entries.py

    - name: Generate image partition
      run: cd custom_logos_uboot && ./03_write_logo_partition.sh

    - name: debug-ls
      run: tree custom_logos_uboot

    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: logo_partition
        path: custom_logos_uboot/logo_new.img

  do_release:
    # if: startsWith(github.ref, 'refs/tags/')
    # if: contains(github.ref, "main")
    runs-on: ubuntu-latest
    needs:
      - compile_uboot
      - generate_spl_boot_file
      - generate_logo_partition
    steps:
      - name: Clone workflow repository
        uses: actions/checkout@v4
      - name: Download image artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            artifacts/rk356x_spl_loader_v1.12.112.bin/rk356x_spl_loader_v1.12.112.bin
            artifacts/uboot-files/uboot.img
            artifacts/uboot-files/trust.img
            artifacts/uboot-files/idblock.bin
            artifacts/data_part_uboot_env/data_part_uboot_env.bin
            artifacts/logo_partition/logo_new.img
